### ISSUE TITLE
Bug with the login

### ISSUE THREAD

**Issue by rspt** [larucheio/transportOne-frontend#168]
To reproduce:
- Go to a page (other than the home page)
- Refresh the page
- Try to login

**Comment by maxirozay** [comment]
I added all the urls in the allowed callback on auth0 and it fix the bug.

**Comment by rspt** [comment]
Does it exist another solution? It's more an hack than a "good" solutions. What if we add some pages, we will need to also think about adding it to Auth0 ^^

**Comment by maxirozay** [comment]
[solution](https://auth0.com/forum/t/using-wildcards-on-callback-urls/249/3) we would need to have only the page transportone.ch/ then all the subpages would be just states and we would use the state parameter.

**Comment by maxirozay** [comment]
I found another solution that redirect on the main page I'll upload it.

**Comment by maxirozay** [comment]
https://auth0.com/docs/protocols/oauth2/oauth-web-protocol I will redirect every pages to transportone.ch

**Comment by rspt** [comment]
Fixed by #169
