### ISSUE TITLE
footer doesn't stick to bottom

### ISSUE THREAD

**Issue by maxirozay** [larucheio/transportOne-frontend#171]
![screenshot from 2017-04-17 14 49 36](https://cloud.githubusercontent.com/assets/12101710/25089351/291a90d4-237d-11e7-8710-492592aeea74.png)

I can't reproduce it but I wanted to let you know I think you can close the issue if you don't have it on your device.

**Comment by rspt** [comment]
Can't reproduce it either. Please repoen if you've got more info about it!
